### ISSUE TITLE
Grails 2.4.3 cant refresh dependencies

### ISSUE THREAD

**Issue by confile** [burtbeckwith/grails-app-info#4]
I use Grails 2.4.3 and added
compile (":app-info:1.1.1")
{ excludes 'jquery' }
When I do refresh-dependencies I got the following error:

```
|Compiling 339 source files
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] /Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 3: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]  @ line 3, column 1.
  [groovyc]    import org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 13: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder 
  [groovyc]  @ line 13, column 32.
  [groovyc]         boolean hasResourcesPlugin = PluginManagerHolder.pluginManager.hasGrailsPlugin('resources')
  [groovyc]                                   ^
  [groovyc] 
  [groovyc] /Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 29: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder 
  [groovyc]  @ line 29, column 32.
  [groovyc]         boolean hasResourcesPlugin = PluginManagerHolder.pluginManager.hasGrailsPlugin('resources')
  [groovyc]                                   ^
  [groovyc] 
  [groovyc] 3 errors

.Error 
|
Compilation error: startup failed:
/Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 3: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder
 @ line 3, column 1.
   import org.codehaus.groovy.grails.plugins.PluginManagerHolder
   ^
/Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 13: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder 
 @ line 13, column 32.
        boolean hasResourcesPlugin = PluginManagerHolder.pluginManager.hasGrailsPlugin('resources')
                                  ^
/Users/mg/Documents/Grails/GGTS3.6.2/test/target/work/plugins/app-info-1.1.1/grails-app/taglib/com/burtbeckwith/grails/plugins/appinfo/AppInfoTagLib.groovy: 29: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder 
 @ line 29, column 32.
        boolean hasResourcesPlugin = PluginManagerHolder.pluginManager.hasGrailsPlugin('resources')
                                  ^
3 errors
```

**Comment by clessiomendes** [comment]
So, is the plugin updated to 2.4+ ?

**Comment by xavs** [comment]
Is the pluginManager change enough for this to work on 2.4?
